
services:
  ssh-server:
    # build:
    #   context: ./dev_ssh-server
      # args:
      #   SSH_USER: ${SSH_USER}
      #   SSH_PASS: ${SSH_PASS}
    image: taothong/u-ssh-server:1.0
    ports:
      - "2222:22"
    volumes:
      - ./main_data:/home/${SSH_USER}
      - ./dev_ssh-server/ssh/sshd_config:/etc/ssh/sshd_config:ro
      - ./dev_ssh-server/ssh/authorized_keys:/home/${SSH_USER}/.ssh/authorized_keys:ro
    restart: unless-stopped
    container_name: ssh-server


  filebrowser:
      ports:
          - 8080:80
      restart: unless-stopped            
      image: filebrowser/filebrowser:s6
      # environment:
      #     - PUID=1000
      #     - PGID=1000
      # user: "true"        
      volumes:
          - ./main_data:/srv
          # - ./filebrowser.db:/database/filebrowser.db        
          - ./filebrowser_settings.json:/config/settings.json
      container_name: filebrowser


  jupyter:
    build:
      context: ./dev_jupyter
      dockerfile: dockerfile_almalinux
    # image: taothong/u-jupyter:1.0
    ports:
      - "8888:8888"
    volumes:
      - ./main_data:/home/master/nas
      - ./dev_jupyter/requirements_python.txt:/home/master/requirements_python.txt
      - ./dev_jupyter/requirements_java.txt:/home/master/requirements_java.txt
      - ./dev_jupyter/dockerfile:/home/master/dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=master
    container_name: jupyter
    # command: jupyter lab --ip=0.0.0.0 --no-browser --NotebookApp.token=${JUPYTER_TOKEN}
    command: jupyter lab --ip=0.0.0.0 --no-browser --NotebookApp.token=${JUPYTER_TOKEN} --NotebookApp.notebook_dir=/home/master/
# docker exec -it jupyter ls
# docker logs jupyter 
